// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart'
    show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCufKN1AcSiOFaeNsP803Ow9riFX2nBnlk',
    appId: '1:881060104990:android:ece22f686f319294d5d70f',
    messagingSenderId: '881060104990',
    projectId: 'taest-db203',
    authDomain: 'taest-db203.firebaseapp.com',
    storageBucket: 'taest-db203.appspot.com',
    // measurementId: 'G-YW5EG1LDRL',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCufKN1AcSiOFaeNsP803Ow9riFX2nBnlk',
    appId: '1:881060104990:android:ece22f686f319294d5d70f',
    messagingSenderId: '881060104990',
    projectId: 'taest-db203',
    storageBucket: 'taest-db203.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCHJ7QClnIy_zM4-eQyRjuUuqx62wWiR6s',
    appId: '1:80078589156:ios:0bf807b81beea1523e30f1',
    messagingSenderId: '80078589156',
    projectId: 'chat-92d56',
    storageBucket: 'chat-92d56.appspot.com',
    iosClientId:
        '80078589156-od1eglniccojel1ob9hjtvsuo2ngikkf.apps.googleusercontent.com',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCHJ7QClnIy_zM4-eQyRjuUuqx62wWiR6s',
    appId: '1:80078589156:ios:0bf807b81beea1523e30f1',
    messagingSenderId: '80078589156',
    projectId: 'chat-92d56',
    storageBucket: 'chat-92d56.appspot.com',
    iosClientId:
        '80078589156-od1eglniccojel1ob9hjtvsuo2ngikkf.apps.googleusercontent.com',
    iosBundleId: 'com.example.chatApp',
  );
}
